version: '3'
services:
  node-app:
    container_name: node-container
    build: 
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: redis