version: '3'
services:
  node-app:
    container_name: node-container
    build: 
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    depends_on:
      - node_db
      - node_db_2

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_USER: example
      POSTGRES_PASSWORD: root
    volumes:
      - node_db_data:/var/lib/postgresql/data


  node_db_2:
    container_name: node_db_2
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_USER: example
      POSTGRES_PASSWORD: root
    volumes:
      - node_db_data_2:/var/lib/postgresql/data



volumes:
  node_db_data: {}
  node_db_data_2: {}